name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log commit
        run: |
          echo "🧠 Building from commit: ${{ github.sha }}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image with unique tag
        run: |
          docker build --no-cache \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/flux:v1-${{ github.run_number }} \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/flux:latest \
            .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flux:v1-${{ github.run_number }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/flux:latest
